# Generated by Django 2.2.7 on 2019-11-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='nom',
        ),
    ]
